######################################################################
# Automatically generated by qmake (3.0) Sun Mar 27 16:04:50 2016
######################################################################
QT += widgets
TEMPLATE = app
TARGET = SmartImageComparison
INCLUDEPATH += .

# Input
HEADERS += compareimage.h generatehah.h mainwindow.h
FORMS += compareimage.ui \
         generatehah.ui \
         mainwindow.ui
SOURCES += compareimage.cpp generatehah.cpp main.cpp mainwindow.cpp
