######################################################################
# Automatically generated by qmake (3.0) Sun Mar 27 16:04:50 2016
######################################################################
QT += widgets
TEMPLATE = app
TARGET = SmartImageComparison
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h gpg.h
FORMS += \
         mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
